"""
pfmr.sandbox.manifest
~~~~~~~~~~~~~~~~~~~~~~
Generates the test Flatpak manifest (org.pfmr.TestSandbox) and the
companion infoscript.sh used inside the sandbox.

The manifest is derived from the target app's runtime/SDK settings so
the probe environment exactly mirrors the real build environment.

Base structure (from spec §18.2):
  app-id: org.pfmr.TestSandbox
  runtime: org.freedesktop.Platform
  sdk: org.freedesktop.Sdk
  command: infoscript.sh
  finish-args: [--share=ipc, --socket=fallback-x11, ...]
  modules:
    - name: infoscript
      buildsystem: simple
      build-commands:
        - install -D infoscript.sh /app/bin/infoscript.sh
      sources:
        - type: file
          path: infoscript.sh

The infoscript.sh serves as:
  1. A sentinel that the sandbox built successfully
  2. A hook point for runtime environment inspection

Additional probe modules can be injected (e.g. python-venv-setup,
pip-install-test) by callers before the manifest is written to disk.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Optional

from pfmr.utils.logging import get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# infoscript.sh content
# ---------------------------------------------------------------------------

INFOSCRIPT_SH = textwrap.dedent("""\
    #!/bin/sh
    # infoscript.sh — pfmr test sandbox probe script
    # Generated by pfmr. Do not edit manually.
    #
    # This script runs inside the Flatpak sandbox and reports
    # environment information useful for dependency probing.

    echo "=== pfmr TestSandbox ==="
    echo "date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "runtime: ${FLATPAK_ID:-unknown}"
    echo "arch: $(uname -m)"
    echo "kernel: $(uname -r)"
    echo ""

    echo "=== Python ==="
    if command -v python3 >/dev/null 2>&1; then
        python3 --version
        echo "python3_path: $(command -v python3)"
    else
        echo "python3: not found"
    fi
    echo ""

    echo "=== pkg-config ==="
    if command -v pkg-config >/dev/null 2>&1; then
        pkg-config --version
        echo "pkg-config: available"
    else
        echo "pkg-config: not found"
    fi
    echo ""

    echo "=== Compiler ==="
    if command -v gcc >/dev/null 2>&1; then
        gcc --version | head -1
    else
        echo "gcc: not found"
    fi
    echo ""

    echo "=== Environment ==="
    env | grep -E '^(PATH|PKG_CONFIG_PATH|LD_LIBRARY_PATH|PYTHONPATH|CARGO|RUST|JAVA|LLVM|GO)' | sort
    echo ""

    echo "=== pfmr TestSandbox ready ==="
""")


# ---------------------------------------------------------------------------
# Manifest builder
# ---------------------------------------------------------------------------

class TestManifestBuilder:
    """
    Builds the org.pfmr.TestSandbox manifest and writes it to a work directory.

    Usage::

        builder = TestManifestBuilder(
            runtime="org.freedesktop.Platform",
            runtime_version="24.08",
            sdk="org.freedesktop.Sdk",
            sdk_extensions=["org.freedesktop.Sdk.Extension.rust-stable"],
        )
        manifest_path = builder.write(work_dir)
    """

    APP_ID = "org.pfmr.TestSandbox"

    def __init__(
        self,
        runtime: str = "org.freedesktop.Platform",
        runtime_version: str = "24.08",
        sdk: str = "org.freedesktop.Sdk",
        sdk_extensions: Optional[list[str]] = None,
        # Extra modules to append after infoscript (probe steps)
        extra_modules: Optional[list[dict]] = None,
    ):
        self.runtime = runtime
        self.runtime_version = runtime_version
        self.sdk = sdk
        self.sdk_extensions = sdk_extensions or []
        self.extra_modules = extra_modules or []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def write(self, work_dir: Path) -> tuple[Path, Path]:
        """
        Write the manifest JSON and infoscript.sh to work_dir.
        Returns (manifest_path, infoscript_path).
        """
        work_dir.mkdir(parents=True, exist_ok=True)

        infoscript_path = work_dir / "infoscript.sh"
        infoscript_path.write_text(INFOSCRIPT_SH)
        infoscript_path.chmod(0o755)

        manifest = self._build_manifest(work_dir)
        manifest_path = work_dir / "org.pfmr.TestSandbox.json"
        manifest_path.write_text(json.dumps(manifest, indent=2))

        logger.debug("Wrote test manifest to %s", manifest_path)
        return manifest_path, infoscript_path

    def manifest_dict(self, work_dir: Path) -> dict:
        """Return the manifest as a plain dict (without writing to disk)."""
        return self._build_manifest(work_dir)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _build_manifest(self, work_dir: Path) -> dict:
        manifest: dict = {
            "app-id": self.APP_ID,
            "runtime": self.runtime,
            "runtime-version": self.runtime_version,
            "sdk": self.sdk,
            "command": "infoscript.sh",
            "finish-args": [
                "--share=ipc",
                "--socket=fallback-x11",
                "--device=dri",
                "--socket=wayland",
                "--share=network",
            ],
        }

        if self.sdk_extensions:
            manifest["sdk-extensions"] = self.sdk_extensions

        infoscript_module = {
            "name": "infoscript",
            "buildsystem": "simple",
            "build-commands": [
                "install -D infoscript.sh /app/bin/infoscript.sh",
            ],
            "sources": [
                {
                    "type": "file",
                    "path": "infoscript.sh",
                }
            ],
        }

        manifest["modules"] = [infoscript_module] + list(self.extra_modules)
        return manifest